using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Engines;
using EFCore.BulkExtensions;
using Microsoft.EntityFrameworkCore;
using PgYeet;

namespace Bench;

// Monitoring strategy = one real insert per measured iteration (no million-invocation auto-tuning),
// which is what you want for a DB benchmark. Each iteration starts from an empty table.
[MemoryDiagnoser]
[SimpleJob(RunStrategy.Monitoring, warmupCount: 3, iterationCount: 10)]
public class InsertBenchmark
{
    [Params(1_000, 10_000, 100_000)]
    public int RowCount;

    private BenchDbContext _db = null!;
    private User[] _users = null!;

    [GlobalSetup]
    public void GlobalSetup()
    {
        // Self-contained schema (needs the Docker Postgres up).
        using var db = new BenchDbContext();
        db.Database.ExecuteSqlRaw(
            """
            CREATE TABLE IF NOT EXISTS users (
                "Id"        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "Name"      character varying(200) NOT NULL,
                "Email"     character varying(320) NOT NULL,
                "IsActive"  boolean NOT NULL,
                "CreatedAt" timestamp with time zone NOT NULL
            );
            """);
    }

    [IterationSetup]
    public void IterationSetup()
    {
        _db = new BenchDbContext();
        _db.Database.ExecuteSqlRaw("TRUNCATE TABLE users RESTART IDENTITY;");

        _users = new User[RowCount];
        for (var i = 0; i < RowCount; i++)
        {
            _users[i] = new User
            {
                Name = "user_" + i,
                Email = Guid.NewGuid().ToString("N") + "@example.com",
                IsActive = true,
                CreatedAt = DateTime.UtcNow,
            };
        }
    }

    [IterationCleanup]
    public void IterationCleanup() => _db.Dispose();

    [Benchmark(Baseline = true)]
    public async Task EfCore_AddRange()
    {
        _db.Users.AddRange(_users);
        await _db.SaveChangesAsync();
    }

    [Benchmark]
    public async Task PgYeet_Copy()
    {
        await _db.Users.YeetAsync(_users);
    }

    [Benchmark]
    public async Task PgYeet_Copy_NoIds()
    {
        await _db.Users.YeetAsync(_users, returnGeneratedKeys: false);
    }

    [Benchmark]
    public Task BulkExtensions_Insert()
    {
        // default config: straight COPY, no key write-back (compare to PgYeet_Copy_NoIds)
        return _db.BulkInsertAsync(_users);
    }

    [Benchmark]
    public Task BulkExtensions_Insert_OutputId()
    {
        // SetOutputIdentity: temp table + RETURNING, keys written back (compare to PgYeet_Copy)
        return _db.BulkInsertAsync(_users, new BulkConfig { SetOutputIdentity = true });
    }
}
